### ISSUE TITLE
Gmod action music creator quits unexpectly

### ISSUE THREAD

**Issue by Cbr2011** [relaxtakenotes/gm-action-music#1]
I don't know why.

**Comment by relaxtakenotes** [comment]
send output.log

**Comment by Cbr2011** [comment]
```
Warning: Unable to set VSync! SDL Error: wglSwapIntervalEXT(): The operation completed successfully.
Traceback (most recent call last):
  File "main.py", line 22, in main
  File "main.py", line 140, in impl_pysdl2_init
NameError: name 'exit' is not defined
```
